---
- name: error handling
  hosts: ubuntu
  user: anisble
  become: yes
  tasks:
    - command: "ls /homee"
      register: home_out
      ignore_errors: yes
    - debug: var=home_out
    - command: "ls /tmp"
      register: tmp_out
    - debug: var=tmp_out
