---
- hosts: dev
  user: ansible
  become: true
  tasks:
    - name: Install EPEL
      yum:
        name: epel-release
        update_cache: yes
        state: latest
      when: ansible_distribution == 'CentOS'
    - name: Install Nginx CentOS
      yum:
        name: nginx
        update_cache: yes
        state: latest
      when: ansible_distribution == 'CentOS'
    - name: Install Nginx Ubuntu
      apt:
        name: nginx
        update_cache: yes
        state: latest
      when: ansible_distribution == 'Ubuntu'
    - name: copy index.html to centos
      ansible.builtin.copy:
        src: index.html
        dest: /usr/share/nginx/html/index.html
      when: ansible_distribution == 'CentOS'
    - name: copy index.html to ubuntu
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html/index.html
      when: ansible_distribution == 'Ubuntu'
    - name: Start NGiNX
      service:
        name: nginx
        state: started
