---
- name: UnInstall nginx
  hosts: centos
  become: true

  tasks:
  - name: Add epel-release repo
    yum:
      name: epel-release
      state: absent

  - name: Install nginx
    yum:
      name: nginx
      state: absent

  - name: Insert Index Page
    template:
      src: index.html
      dest: /usr/share/nginx/html/index.html

  - name: Start NGiNX
    service:
      name: nginx
      state: started

