---
-
  hosts: dev
  user: ansible
  become: true
  tasks:
    - name: Deleting user
      user:
        name: "{{ item }}"
        state: absent		
      with_items: 
        - manjith
        - karthick
        - murali
